// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://sjeybaryajvbdaozqwio.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZXliYXJ5YWp2YmRhb3pxd2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MDQ3MDUsImV4cCI6MjA0OTA4MDcwNX0.stozOkekJwrlokEz2NyROZJUzcCVOQZiLHpEP2Uhmv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);